spring.application.name=Restaurant-Ordering-Sim-Backend

spring.datasource.url=jdbc:mysql://localhost:3306/restaurant_simulation_db
spring.datasource.username=root
spring.datasource.password=sammyshet

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# spring.jpa.show-sql=true
